name: VirtualHere Client
version: "0.3.0"
slug: vhclient
description: VirtualHere Client
arch:
  - armhf
  - aarch64
  - amd64
  - i386
url: "https://github.com/hans99/home-assistant-addons"
startup: services
host_network: true
hassio_api: true
homeassistant_api: true
privileged:
  - SYS_ADMIN
apparmor: false
map:
  - type: homeassistant_config
    read_only: false
    path: /config
usb: true
kernel_modules: true
options:
  autouse: true
  autofind: true
  usbdevices: []
  preventconfig: false
schema:
  autouse: bool
  autofind: bool
  usbdevices: [{
    device: str?,
    use: bool?
  }]
  preventconfig: bool
  clientid: str?
  manualhub: str?
stage: stable
init: false

